"""Monthly reports with a versioned profile library and a synthetic demonstration.

The owner deferred passcodes during internal testing; shared library writes
still require explicit confirmation and remain attributable and reversible.
"""

from __future__ import annotations

from dataclasses import replace
from datetime import date

import streamlit as st

from app.config import operator_today
from app.monthly_report_checks import preflight
from app.monthly_report_docx import generate_report, outline
from app.monthly_report_model import ReportPeriod, synthetic_draft, synthetic_profiles
from app.ui_highlight import highlight_needed_fields


MONTHLY_REPORT_WORKFLOW = "Monthly report"


def preserve_report_draft_state() -> None:
    """Mirror registered operator fields before Streamlit cleans hidden widgets.

    Explicit registration avoids retaining generated bytes, errors or future AI
    jobs just because their keys also start with report_. Additive merging keeps
    per-profile edits when another profile's fields are the ones on screen.
    """
    mirror = dict(st.session_state.get("report_draft_mirror", {}))
    for key in st.session_state.get("report_widget_keys", ()):
        if key in st.session_state:
            value = st.session_state[key]
            if isinstance(value, (str, bool, int, float, date, tuple, list)):
                mirror[key] = value
    st.session_state["report_draft_mirror"] = mirror


def restore_report_draft_state() -> None:
    for key, value in st.session_state.get("report_draft_mirror", {}).items():
        st.session_state.setdefault(key, value)


def _field(key: str, default):
    registered = set(st.session_state.get("report_widget_keys", ()))
    registered.add(key)
    st.session_state["report_widget_keys"] = tuple(sorted(registered))
    st.session_state.setdefault(key, default)
    return key


def _move(order_key: str, section_key: str, offset: int) -> None:
    order = list(st.session_state[order_key])
    index = order.index(section_key)
    target = index + offset
    if 0 <= target < len(order):
        order[index], order[target] = order[target], order[index]
        st.session_state[order_key] = order
    preserve_report_draft_state()


def render_monthly_report_workflow(browser_token: str, browser_timezone: str = "") -> None:
    """Keep library and demonstration work separate while preserving both drafts."""
    restore_report_draft_state()
    st.title("Monthly report")
    if st.toggle("Use the profile library", key=_field("report_use_library", False)):
        from app.monthly_report_editor import render_profile_workflow
        try:
            render_profile_workflow(browser_token, browser_timezone, _field, _move)
        except (ValueError, OSError) as exc:
            st.error(f"The profile library could not be read: {exc}")
        preserve_report_draft_state()
        return
    st.info("Explore individual, multi-site and regional layouts with synthetic content, or turn on the profile library above to build your report. Document import and AI drafts are coming next.")
    st.subheader("1. Choose the report")
    profiles = synthetic_profiles()
    profile_key = st.selectbox("Report profile", [p.key for p in profiles],
                              format_func=lambda key: next(p.title for p in profiles if p.key == key),
                              key=_field("report_profile", profiles[0].key))
    profile = next(p for p in profiles if p.key == profile_key)
    st.caption(f"Contract: {profile.contract} · Scope: {profile.scope_type.replace('_', ' ')}")
    st.write("Facilities: " + "; ".join(f.title for f in profile.facilities))
    default_period = ReportPeriod.previous(operator_today(browser_timezone))
    selected = st.date_input("Reporting month", key=_field("report_month", default_period.start),
                             help="Choose any day in the reporting month; the report covers the full calendar month.")
    period = ReportPeriod(selected.year, selected.month)
    st.caption(f"Reporting period: {period.start.strftime('%b %-d, %Y')} – {period.end.strftime('%b %-d, %Y')}")
    base = synthetic_draft(profile, period)
    prefix = f"report_{profile.key}"
    prepared_key = _field(f"{prefix}_prepared_by", base.prepared_by)
    prepared_by = st.text_input("Prepared by", key=prepared_key)
    st.caption("Starting from the synthetic library template. Monthly uploads, Copilot context and AI drafts are not enabled in this milestone.")

    st.subheader("5. Assemble the report")
    st.write("Edit the demonstration text, include or omit sections, and set their order. The contents and divider numbers follow your choices.")
    order_key = _field(f"{prefix}_order", [s.key for s in base.sections])
    by_key = {s.key: s for s in base.sections}
    sections = []
    blocks = []
    base_blocks = {b.key: b for b in base.blocks}
    needed_keys = []
    for position, key in enumerate(st.session_state[order_key]):
        section = by_key[key]
        section_prefix = f"{prefix}_{key}"
        with st.expander(section.title):
            include = st.toggle("Include section", key=_field(f"{section_prefix}_include", section.included))
            left, right = st.columns(2)
            left.button("Move up", key=f"{section_prefix}_up", disabled=position == 0,
                        on_click=_move, args=(order_key, key, -1), width="stretch")
            right.button("Move down", key=f"{section_prefix}_down", disabled=position == len(by_key) - 1,
                         on_click=_move, args=(order_key, key, 1), width="stretch")
            title = st.text_input("Section title", key=_field(f"{section_prefix}_title", section.title))
            block = base_blocks[section.blocks[0].key]
            text_key = _field(f"{section_prefix}_text", block.text)
            text = st.text_area("Section text", key=text_key, height=130,
                                help="Use one paragraph per line, '- ' for bullets, or '## ' for a subheading.")
            if include and not text.strip():
                needed_keys.append(text_key)
            if include and not title.strip():
                needed_keys.append(f"{section_prefix}_title")
            sections.append(replace(section, included=include, title=title))
            blocks.append(replace(block, text=text))
    draft = replace(base, prepared_by=prepared_by, sections=tuple(sections), blocks=tuple(blocks))
    with st.expander("Live outline"):
        for title, block_keys, pages in outline(draft):
            st.write(title)
            st.caption(f"{', '.join(block_keys)} · at least {pages} pages including divider")
        st.caption(f"At least {2 + sum(item[2] for item in outline(draft))} pages including cover and contents. Long text may need more pages.")

    st.subheader("6. Check and generate")
    checks = preflight(draft)
    blocking = [c for c in checks if c.blocking]
    warnings = [c for c in checks if not c.blocking]
    for check in blocking:
        st.error(check.message)
    for check in warnings:
        st.warning(check.message)
    acknowledged = False
    if warnings:
        # A new draft gets a new checkbox; a stale acknowledgement is unusable.
        acknowledged = st.checkbox("I've checked these warnings", key=f"report_ack_{draft.fingerprint}")
    if not prepared_by.strip():
        needed_keys.append(prepared_key)
    highlight_needed_fields(needed_keys)
    package = st.session_state.get("report_package")
    if package and package.fingerprint != draft.fingerprint:
        st.session_state.pop("report_package", None)
        package = None
    if st.button("Generate DOCX and PDF", key="report_generate", type="primary",
                 disabled=bool(blocking or (warnings and not acknowledged))):
        try:
            with st.spinner("Assembling DOCX and converting PDF…"):
                package = generate_report(draft, acknowledged_fingerprint=draft.fingerprint if acknowledged else "")
            st.session_state["report_package"] = package
        except (ValueError, OSError) as exc:
            st.error(f"Report could not be assembled: {exc}")
    if package:
        st.download_button("Download DOCX", package.docx, file_name=package.docx_name,
                           mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document", key="report_download_docx")
        if package.pdf:
            st.download_button("Download PDF", package.pdf, file_name=package.pdf_name,
                               mime="application/pdf", key="report_download_pdf")
        if package.pdf_error:
            st.warning(package.pdf_error)
    preserve_report_draft_state()
